# 10.Assignment (10)_Recommendation System


Que.No.1) Problem statement.

Build a recommender system by using cosine simillarties score. Dataset(Book)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling as pp
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
book = pd.read_csv("books.csv")

In [3]:
book

Unnamed: 0  User.ID                                         Book.Title  \
0              1   276726                                Classical Mythology   
1              2   276729                                       Clara Callan   
2              3   276729                               Decision in Normandy   
3              4   276736  Flu: The Story of the Great Influenza Pandemic...   
4              5   276737                             The Mummies of Urumchi   
...          ...      ...                                                ...   
9995        9996   162121       American Fried: Adventures of a Happy Eater.   
9996        9997   162121                              Cannibal In Manhattan   
9997        9998   162121                    How to Flirt: A Practical Guide   
9998        9999   162121                                           Twilight   
9999       10000   162129                       Kids Say the Darndest Things   

      Book.Rating  
0               5  
1               3  
2               6  
3               8  
4               6  
...           ...  
9995            7  
9996            9  
9997            7  
9998            8  
9999            6  

[10000 rows x 4 columns]

In [4]:
# taking columns from 1
book1 = book.iloc[:,1:]

In [5]:
book1

User.ID                                         Book.Title  Book.Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [6]:
book2 = book1.rename({'User.ID':'User_ID','Book.Title':'Book_Title','Book.Rating':'Book_Rating'}, axis = 1)

In [7]:
book2

User_ID                                         Book_Title  Book_Rating
0      276726                                Classical Mythology            5
1      276729                                       Clara Callan            3
2      276729                               Decision in Normandy            6
3      276736  Flu: The Story of the Great Influenza Pandemic...            8
4      276737                             The Mummies of Urumchi            6
...       ...                                                ...          ...
9995   162121       American Fried: Adventures of a Happy Eater.            7
9996   162121                              Cannibal In Manhattan            9
9997   162121                    How to Flirt: A Practical Guide            7
9998   162121                                           Twilight            8
9999   162129                       Kids Say the Darndest Things            6

[10000 rows x 3 columns]

In [8]:
#number of unique users in the dataset
len(book2.User_ID.unique())

2182

In [9]:
# Knowing the length of the dataset
len(book2.Book_Title.unique())

9659

In [10]:
# Value count of movies length
book2.Book_Title.value_counts()

Fahrenheit 451                                              5
Charlie and the Chocolate Factory                           4
The Subtle Knife (His Dark Materials, Book 2)               4
Vanished                                                    4
Ender's Game (Ender Wiggins Saga (Paperback))               4
                                                           ..
Murder on St. Mark's Place (Gaslight Mysteries)             1
State of Grace                                              1
Valsalva's Maneuver: Mots Justes and Indispensable Terms    1
I love you, I hate you                                      1
Kids Say the Darndest Things                                1
Name: Book_Title, Length: 9659, dtype: int64

In [11]:
#convrting data from long format to wide format using pivot_table
book3 = book2.pivot_table(index='User_ID',
                            columns='Book_Title',
                            values='Book_Rating').reset_index(drop=True)

In [12]:
book3

Book_Title   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
0                            NaN                                         NaN   
1                            NaN                                         NaN   
2                            NaN                                         NaN   
3                            NaN                                         NaN   
4                            NaN                                         NaN   
...                          ...                                         ...   
2177                         NaN                                         NaN   
2178                         NaN                                         NaN   
2179                         NaN                                         NaN   
2180                         NaN                                         NaN   
2181                         NaN                                         NaN   

Book_Title   Repairing PC Drives &amp  '48  \
0                                 NaN  NaN   
1                                 NaN  NaN   
2                                 NaN  NaN   
3                                 NaN  NaN   
4                                 NaN  NaN   
...                               ...  ...   
2177                              NaN  NaN   
2178                              NaN  NaN   
2179                              NaN  NaN   
2180                              NaN  NaN   
2181                              NaN  NaN   

Book_Title  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
0                                                         NaN                       
1                                                         NaN                       
2                                                         NaN                       
3                                                         NaN                       
4                                                         NaN                       
...                                                       ...                       
2177                                                      NaN                       
2178                                                      NaN                       
2179                                                      NaN                       
2180                                                      NaN                       
2181                                                      NaN                       

Book_Title  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
0                                                         NaN              
1                                                         NaN              
2                                                         NaN              
3                                                         NaN              
4                                                         NaN              
...                                                       ...              
2177                                                      NaN              
2178                                                      NaN              
2179                                                      NaN              
2180                                                      NaN              
2181                                                      NaN              

Book_Title  01-01-00: A Novel of the Millennium  \
0                                           NaN   
1                                           NaN   
2                                           NaN   
3                                           NaN   
4                                           NaN   
...                                         ...   
2177                                        NaN   
2178                                        NaN   
2179                                        NaN   
2180                                      

In [13]:
#Impute those NaNs with 0 values
book3.fillna(0, inplace=True)

In [14]:
book3

Book_Title   Jason, Madison &amp   Other Stories;Merril;1985;McClelland &amp  \
0                            0.0                                         0.0   
1                            0.0                                         0.0   
2                            0.0                                         0.0   
3                            0.0                                         0.0   
4                            0.0                                         0.0   
...                          ...                                         ...   
2177                         0.0                                         0.0   
2178                         0.0                                         0.0   
2179                         0.0                                         0.0   
2180                         0.0                                         0.0   
2181                         0.0                                         0.0   

Book_Title   Repairing PC Drives &amp  '48  \
0                                 0.0  0.0   
1                                 0.0  0.0   
2                                 0.0  0.0   
3                                 0.0  0.0   
4                                 0.0  0.0   
...                               ...  ...   
2177                              0.0  0.0   
2178                              0.0  0.0   
2179                              0.0  0.0   
2180                              0.0  0.0   
2181                              0.0  0.0   

Book_Title  'O Au No Keia: Voices from Hawai'I's Mahu and Transgender Communities  \
0                                                         0.0                       
1                                                         0.0                       
2                                                         0.0                       
3                                                         0.0                       
4                                                         0.0                       
...                                                       ...                       
2177                                                      0.0                       
2178                                                      0.0                       
2179                                                      0.0                       
2180                                                      0.0                       
2181                                                      0.0                       

Book_Title  ...AND THE HORSE HE RODE IN ON : THE PEOPLE V. KENNETH STARR  \
0                                                         0.0              
1                                                         0.0              
2                                                         0.0              
3                                                         0.0              
4                                                         0.0              
...                                                       ...              
2177                                                      0.0              
2178                                                      0.0              
2179                                                      0.0              
2180                                                      0.0              
2181                                                      0.0              

Book_Title  01-01-00: A Novel of the Millennium  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
...                                         ...   
2177                                        0.0   
2178                                        0.0   
2179                                        0.0   
2180                                      

In [15]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [16]:
# sim is none but similarities
user_sim = 1 - pairwise_distances(book3.values,metric='cosine')

In [17]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [18]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_sim)
user_sim_df

0     1     2     3     4     5     6     7     8     9     ...  2172  \
0      1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2177   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2178   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2179   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      2173  2174  2175  2176  2177  2178  2179  2180  2181  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2177   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0   0.0  
2178   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0   0.0  
2179   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0  
2180   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0   0.0  
2181   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  

[2182 rows x 2182 columns]

In [19]:
#assigning unique userid to rows and columns
user_sim_df.index = book2['User_ID'].unique()
user_sim_df.columns = book2['User_ID'].unique()

In [20]:
user_sim_df.iloc[0:5, 0:5]

276726  276729  276736  276737  276744
276726     1.0     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0     0.0
276737     0.0     0.0     0.0     1.0     0.0
276744     0.0     0.0     0.0     0.0     1.0

In [21]:
#filling digonal values
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

In [22]:
#finding users with max similarities
user_sim_df.idxmax(axis=1)

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
           ...  
162107    276726
162109    276726
162113    161453
162121    276726
162129    276726
Length: 2182, dtype: int64

In [23]:
book2[(book2['User_ID']==162129) | (book2['User_ID']==276726)]

User_ID                    Book_Title  Book_Rating
0      276726           Classical Mythology            5
9999   162129  Kids Say the Darndest Things            6

In [24]:
book2[(book2['User_ID']==276737) | (book2['User_ID']==276726)]

User_ID              Book_Title  Book_Rating
0   276726     Classical Mythology            5
4   276737  The Mummies of Urumchi            6

In [25]:
user_1 = book2[(book2['User_ID']==276726)]
user_2 = book2[(book2['User_ID']==276737)]

In [26]:
user_1.Book_Title

0    Classical Mythology
Name: Book_Title, dtype: object

In [27]:
user_2.Book_Title

4    The Mummies of Urumchi
Name: Book_Title, dtype: object

In [28]:
# merging users and recomandaatin demo using random users 
pd.merge(user_1,user_2,on='Book_Title',how = 'outer')

User_ID_x              Book_Title  Book_Rating_x  User_ID_y  Book_Rating_y
0   276726.0     Classical Mythology            5.0        NaN            NaN
1        NaN  The Mummies of Urumchi            NaN   276737.0            6.0

from above table we can recommend book classic mythology to user_1:userid = 276726
and we can recommend The Mummies of Urumchi to user_1:userid = 276737